# Generated by Django 5.1.7 on 2025-04-03 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_engine', '0002_questioncategory_remove_testsectionconfig_num_easy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='show_section_time_guidance',
            field=models.BooleanField(default=False, help_text='Show section-wise time as guidance even if total time is enforced.'),
        ),
        migrations.AlterField(
            model_name='testsectionconfig',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='test_engine.test'),
        ),
    ]
