# Generated by Django 5.1.7 on 2025-04-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_engine', '0004_alter_test_show_section_time_guidance'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='enforce_section_time',
            field=models.BooleanField(default=False),
        ),
    ]
