# Generated by Django 5.1.7 on 2025-04-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_engine', '0005_test_enforce_section_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='marked_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='revisit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('candidate', 'question')},
        ),
    ]
