# Generated by Django 5.1.7 on 2025-04-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_engine', '0014_candidatesectionquestionorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionstatus',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
