# Generated by Django 5.1.7 on 2025-04-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_engine', '0015_sectionstatus_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='secret_code_1',
            field=models.CharField(default='Test_Key_1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='secret_code_2',
            field=models.CharField(default='Test_Key_2', max_length=50),
            preserve_default=False,
        ),
    ]
