# Generated by Django 5.1.7 on 2025-06-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_engine', '0016_candidate_secret_code_1_candidate_secret_code_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetestsession',
            name='screen_ok',
            field=models.BooleanField(default=True),
        ),
    ]
