# Generated by Django 5.1.7 on 2025-06-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_engine', '0017_candidatetestsession_screen_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetestsession',
            name='test_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
