services:
  - type: web
    name: shreds-platform
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn assessments.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: assessments.settings
      - key: PYTHON_VERSION
        value: 3.11.9
      - fromDatabase:
          name: shreds-db
          property: connectionString
          key: DATABASE_URL

databases:
  - name: shreds-db

preDeployCommand: |
  python manage.py dump_users
  python manage.py migrate
  python manage.py collectstatic --noinput
  python manage.py create_initial_superuser

