services:
  - type: web
    name: shreds-platform
    env: python
    plan: free
    rootDir: backend
    staticPublishPath: staticfiles
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py loaddata fixtures/initial_data.json

    preDeployCommand: |
      python manage.py collectstatic --noinput
      echo "== Checking DB users =="
      python manage.py dump_users


    startCommand: gunicorn assessments.wsgi:application

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: assessments.settings
      - key: PYTHON_VERSION
        value: 3.11.9
      - fromDatabase:
          name: shreds-db
          property: connectionString
          key: DATABASE_URL

databases:
  - name: shreds-db
