# Generated by Django 5.1.7 on 2025-05-20 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_engine', '0016_candidate_secret_code_1_candidate_secret_code_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_text', models.TextField()),
                ('agreed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.candidate')),
                ('test_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.testassignment')),
            ],
        ),
        migrations.CreateModel(
            name='ProctoringPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('face', 'Face'), ('id', 'ID Document'), ('signature', 'Signature'), ('violation', 'Violation')], max_length=20)),
                ('image', models.ImageField(upload_to='proctoring_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quality_self_declared', models.BooleanField(default=False)),
                ('quality_flagged_by_admin', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.candidate')),
                ('id_document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proctoring.iddocumenttype')),
                ('test_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.testassignment')),
            ],
        ),
        migrations.CreateModel(
            name='TestProctoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_face_photo', models.BooleanField(default=True)),
                ('require_signature_photo', models.BooleanField(default=False)),
                ('consent_text', models.TextField()),
                ('allowed_id_documents', models.ManyToManyField(to='proctoring.iddocumenttype')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_engine.test')),
            ],
        ),
    ]
