# Generated by Django 5.1.7 on 2025-05-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringphoto',
            name='context',
            field=models.CharField(choices=[('initial', 'Initial Setup'), ('violation', 'Violation Capture'), ('final', 'Final Submission')], default='initial', max_length=20),
        ),
        migrations.AddField(
            model_name='testproctoringconfig',
            name='allow_file_upload',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testproctoringconfig',
            name='require_screen_capture',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proctoringphoto',
            name='photo_type',
            field=models.CharField(choices=[('face', 'Face'), ('id', 'ID Document'), ('signature', 'Signature'), ('screen', 'Screen Snapshot')], max_length=20),
        ),
    ]
