# Generated by Django 5.1.7 on 2025-05-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0002_proctoringphoto_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testproctoringconfig',
            name='allow_file_upload_fallback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testproctoringconfig',
            name='consent_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testproctoringconfig',
            name='live_admin_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testproctoringconfig',
            name='max_upload_size_mb',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='testproctoringconfig',
            name='periodic_face_capture_sec',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='testproctoringconfig',
            name='periodic_screen_capture_sec',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='testproctoringconfig',
            name='quality_profile',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='testproctoringconfig',
            name='require_face_photo_periodic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testproctoringconfig',
            name='require_final_photo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testproctoringconfig',
            name='require_screen_capture_periodic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testproctoringconfig',
            name='violation_boost_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='proctoringphoto',
            name='context',
            field=models.CharField(choices=[('initial', 'Initial Setup'), ('periodic', 'Periodic Monitoring'), ('violation', 'Violation Capture'), ('final', 'Final Submission')], default='initial', max_length=20),
        ),
    ]
