# Generated by Django 5.1.7 on 2025-05-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0003_testproctoringconfig_allow_file_upload_fallback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testproctoringconfig',
            name='allow_file_upload',
        ),
        migrations.RemoveField(
            model_name='testproctoringconfig',
            name='require_screen_capture',
        ),
        migrations.AddField(
            model_name='testproctoringconfig',
            name='require_id_photo',
            field=models.BooleanField(default=True),
        ),
    ]
