# Generated by Django 5.1.7 on 2025-05-22 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0004_remove_testproctoringconfig_allow_file_upload_and_more'),
        ('test_engine', '0016_candidate_secret_code_1_candidate_secret_code_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('screen_sharing_ok', models.BooleanField(default=False)),
                ('camera_streaming_ok', models.BooleanField(default=False)),
                ('fullscreen_mode', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.candidate')),
                ('test_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.testassignment')),
            ],
            options={
                'unique_together': {('candidate', 'test_assignment')},
            },
        ),
    ]
