# Generated by Django 5.1.7 on 2025-06-04 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0005_proctoringsession'),
        ('test_engine', '0016_candidate_secret_code_1_candidate_secret_code_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('camera_lost', 'Camera Feed Lost'), ('screen_lost', 'Screen Share Lost'), ('fullscreen_exit', 'Fullscreen Exited'), ('face_mismatch', 'Face Mismatch'), ('multiple_faces', 'Multiple Faces'), ('no_face', 'No Face Detected'), ('keyboard_activity', 'Prohibited Keyboard Activity'), ('other', 'Other')], max_length=64)),
                ('severity', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.testassignment')),
            ],
        ),
    ]
