# Generated by Django 5.1.7 on 2025-06-04 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0006_proctoringviolation'),
        ('test_engine', '0016_candidate_secret_code_1_candidate_secret_code_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoringviolation',
            name='violation_type',
            field=models.CharField(choices=[('camera_lost', 'Camera Feed Lost'), ('camera_capture_failed', 'Camera Capture Failed'), ('screen_lost', 'Screen Share Lost'), ('screen_capture_failed', 'Screen Capture Failed'), ('fullscreen_exit', 'Fullscreen Exited'), ('face_mismatch', 'Face Mismatch'), ('multiple_faces', 'Multiple Faces'), ('no_face', 'No Face Detected'), ('keyboard_activity', 'Prohibited Keyboard Activity'), ('tab_switch', 'Tab Switch or Blur'), ('right_click', 'Right Click Detected'), ('other', 'Other')], max_length=64),
        ),
        migrations.CreateModel(
            name='ProctoringHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('severity_score', models.IntegerField(default=0)),
                ('last_face_photo_url', models.URLField(blank=True, null=True)),
                ('last_face_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_face_capture_ok', models.BooleanField(default=True)),
                ('last_screen_photo_url', models.URLField(blank=True, null=True)),
                ('last_screen_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_screen_ok', models.BooleanField(default=True)),
                ('fullscreen_ok', models.BooleanField(default=True)),
                ('fullscreen_exit_time', models.DateTimeField(blank=True, null=True)),
                ('candidate_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('test_started_at', models.DateTimeField(blank=True, null=True)),
                ('test_completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.testassignment')),
            ],
        ),
    ]
