# Generated by Django 5.1.7 on 2025-06-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0007_alter_proctoringviolation_violation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringheartbeat',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='proctoringviolation',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
    ]
