# Generated by Django 5.1.7 on 2025-06-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0008_proctoringheartbeat_attempt_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proctoringheartbeat',
            name='attempt_number',
        ),
    ]
