# Generated by Django 5.1.7 on 2025-06-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0009_remove_proctoringheartbeat_attempt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringheartbeat',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
    ]
