# Generated by Django 5.1.7 on 2025-06-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0010_proctoringheartbeat_attempt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringheartbeat',
            name='total_camera_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proctoringheartbeat',
            name='total_fullscreen_exits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proctoringheartbeat',
            name='total_heartbeat_polls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proctoringheartbeat',
            name='total_screen_failures',
            field=models.IntegerField(default=0),
        ),
    ]
