# Generated by Django 5.1.7 on 2025-06-05 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0011_proctoringheartbeat_total_camera_failures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringheartbeat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 5, 18, 28, 0, 368208, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
