# Generated by Django 5.1.7 on 2025-04-02 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('maths', 'Maths / Arithmetic / Geometry / Trigonometry'), ('gk', 'General Knowledge'), ('verbal', 'Verbal Ability / Comprehension'), ('logical', 'Logical Reasoning'), ('di', 'Data Sufficiency / Data Interpretation'), ('coding', 'Coding Skills')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], max_length=10)),
                ('question_type', models.CharField(default='MCQ', max_length=50)),
                ('options', models.TextField(help_text='Enter choices as JSON: ["A", "B", "C", "D"]')),
                ('correct_answer', models.TextField()),
                ('positive_marks', models.FloatField(default=1.0)),
                ('negative_marks', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_duration_minutes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.question')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.candidate')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='test_engine.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('maths', 'Maths / Arithmetic / Geometry / Trigonometry'), ('gk', 'General Knowledge'), ('verbal', 'Verbal Ability / Comprehension'), ('logical', 'Logical Reasoning'), ('di', 'Data Sufficiency / Data Interpretation'), ('coding', 'Coding Skills')], max_length=20)),
                ('num_easy', models.IntegerField(default=0)),
                ('num_moderate', models.IntegerField(default=0)),
                ('num_hard', models.IntegerField(default=0)),
                ('section_duration_minutes', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='test_engine.test')),
            ],
        ),
    ]
