# Generated by Django 5.1.7 on 2025-04-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_engine', '0003_test_show_section_time_guidance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='show_section_time_guidance',
            field=models.BooleanField(default=False),
        ),
    ]
