# Generated by Django 5.1.7 on 2025-04-03 12:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_engine', '0006_response_marked_for_review_response_revisit_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('section_started_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.candidate')),
                ('current_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_engine.testsectionconfig')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.test')),
            ],
        ),
    ]
