# Generated by Django 5.1.7 on 2025-04-03 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_engine', '0007_candidatetestsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorereport',
            name='total',
        ),
        migrations.AddField(
            model_name='scorereport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scorereport',
            name='total_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorereport',
            name='total_negative',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='scorereport',
            name='total_positive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='scorereport',
            name='total_unattempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorereport',
            name='total_wrong',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scorereport',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
