# Generated by Django 5.1.7 on 2025-04-04 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_engine', '0009_response_answered_at_alter_scorereport_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='response',
            name='test',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='test_engine.test'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('candidate', 'question', 'test')},
        ),
    ]
