# Generated by Django 5.1.7 on 2025-04-05 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_engine', '0013_alter_candidatetestsession_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSectionQuestionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.testsectionconfig')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.candidatetestsession')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('session', 'section', 'question')},
            },
        ),
    ]
