# Generated by Django 5.1.7 on 2025-04-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_engine', '0008_remove_scorereport_total_scorereport_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='answered_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scorereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
