# Generated by Django 5.1.7 on 2025-04-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_engine', '0010_alter_response_unique_together_response_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorereport',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
