# Generated by Django 5.1.7 on 2025-04-05 10:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_engine', '0011_scorereport_max_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='candidatetestsession',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='response',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scorereport',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='response',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='revisit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='response',
            name='time_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scorereport',
            name='total_correct',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='scorereport',
            name='total_negative',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scorereport',
            name='total_positive',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scorereport',
            name='total_unattempted',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='scorereport',
            name='total_wrong',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('candidate', 'question', 'test', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='scorereport',
            unique_together={('candidate', 'test', 'attempt_number')},
        ),
        migrations.CreateModel(
            name='ArchivedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('time_spent', models.PositiveIntegerField(default=0)),
                ('marked_for_review', models.BooleanField(default=False)),
                ('revisit_count', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField()),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.candidate')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.test')),
            ],
            options={
                'unique_together': {('candidate', 'test')},
            },
        ),
        migrations.AddField(
            model_name='candidatetestsession',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_engine.testassignment'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatetestsession',
            unique_together={('assignment', 'attempt_number')},
        ),
        migrations.CreateModel(
            name='SectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('auto_submitted', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.testsectionconfig')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.candidatetestsession')),
            ],
            options={
                'unique_together': {('session', 'section')},
            },
        ),
        migrations.RemoveField(
            model_name='candidatetestsession',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='candidatetestsession',
            name='test',
        ),
    ]
