# Generated by Django 5.1.7 on 2025-04-05 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_engine', '0012_alter_response_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatetestsession',
            name='assignment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='test_engine.testassignment'),
            preserve_default=False,
        ),
    ]
